### ISSUE TITLE
DB Host Connection

### ISSUE THREAD

**Issue by TianMeds** [refactorian/laravel-docker#109]
I was running my laravel backend as usual and already have my docker running. I can access the phpmyadmin and the account stated in the documentation but when i try to migrate my new Migration this what appears. My .env already been set like on the other issue here i tested the host to be in "db" i also try the "127.0.0.1" but both didn't work it can't migrate my migration

![image](https://github.com/refactorian/laravel-docker/assets/99672958/3cd2fb27-a568-4111-8882-10473b237112)

**Comment by refactorian** [comment]
@TianMeds Try the following steps : 

1. `docker compose down`
2. Set `DB_HOST=db` in your `.env`
3. `docker compose up -d`
4. `docker compose exec php bash`
5. `php artisan config:clear`
6. `php artisan migrate`

If it doesn't work, delete everything and create the environment again.

**Comment by refactorian** [comment]
@TianMeds  Try the following steps : 

1. `docker compose down`
2. Set `DB_HOST=db` in your `.env`
3. `docker compose up -d`
4. `docker compose exec php bash`
5. `php artisan config:clear`
6. `php artisan migrate`

If it still doesn't work, delete everything and create the environment again.
