### ISSUE TITLE
Rector

### ISSUE THREAD

**Issue by cth18012017** [refactorian/laravel-docker#28]
Hello would you integrate rectore as code Qualität Tool.

**Comment by refactorian** [comment]
I have added Rector. https://github.com/refactorian/laravel-docker/pull/30
Please configure the `rector.php` file as per your need.

**Comment by refactorian** [comment]
I have added Rector. https://github.com/refactorian/laravel-docker/pull/30
Please modify the `rector.php` file as per your need.
