### ISSUE TITLE
DB-Host problem.

### ISSUE THREAD

**Issue by Skaywalker** [refactorian/laravel-docker#53]
Sorry, I still have a little problem.
 When I migrate the database, I find that the migration is running. But the page is connected to the database.
![image](https://github.com/refactorian/laravel-docker/assets/115165402/22f8b2cf-b052-441a-ab33-9433302eb8cb)
![image](https://github.com/refactorian/laravel-docker/assets/115165402/5f8e55ce-1978-48f6-959a-df5d67831df7)
but if I replace DB-HOST with db, the page runs. But then I can't use the database from my terminal.
I have already added the network settings so that docker can work as a bridge.

Thank you in advance for your help.

**Comment by refactorian** [comment]
@Skaywalker 
Yes, you've to set the `DB_HOST` to `db`. It's written in the `.env.example` 
https://github.com/refactorian/laravel-docker/blob/95797abd4fcce23407436199c58389c07cfa8a5b/.env.example#L22-L27

MySQL is in the `db` container. 

> docker compose exec db bash

Run this to access the db bash. Once you're inside the container you can access MySQL from there.

> mysql -urefactorian -p
> Enter password: (refactorian)
> mysql> SHOW DATABASES;

**Comment by refactorian** [comment]
@Skaywalker 
Yes, you've to set the `DB_HOST` to `db`. It's written in the `.env.example` 
https://github.com/refactorian/laravel-docker/blob/95797abd4fcce23407436199c58389c07cfa8a5b/.env.example#L22-L27

MySQL is in the `db` container. 
Run `docker compose exec db bash` to access it. 
Once you're inside the container you can access MySQL from there.

> mysql -urefactorian -p
> Enter password: (refactorian)
> mysql> SHOW DATABASES;
