### ISSUE TITLE
Vendor not found

### ISSUE THREAD

**Issue by ui-code** [refactorian/laravel-docker#67]
After following the steps in readme, setup was successful in docker. But when I go to http://localhost/, I get this error:

Warning: require(/var/www/public/../vendor/autoload.php): Failed to open stream: No such file or directory in /var/www/public/index.php on line 13

Fatal error: Uncaught Error: Failed opening required '/var/www/public/../vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /var/www/public/index.php:13 Stack trace: #0 {main} thrown in /var/www/public/index.php on line 13

I looked for `vendor` folder, it's not present. It's ignored in gitignore file.

**Comment by refactorian** [comment]
It works on my machine ¯\_(ツ)_/¯

**Comment by refactorian** [comment]
It works on my machine 🤷‍♂️
