### ISSUE TITLE
SQLSTATE[HY000] [2002] Connection refused

### ISSUE THREAD

**Issue by soheylfarzane** [refactorian/laravel-docker#70]
**when run project get this error SQLSTATE[HY000] [2002] Connection refused**
everything is ok
php myadmin is running 
connected to there and see table 
but get this error

**Comment by refactorian** [comment]
@soheylfarzane 
How did you run the project? 
Could you tell me the steps?

**Comment by soheylfarzane** [comment]
i found it the name of DB_HOST must db
